version: "3.9"

services:
  db:
    image: postgres:16
    container_name: project_postgres
    restart: always
    env_file:
      - backend/.env
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/db:/docker-entrypoint-initdb.d


volumes:
  postgres_data:
